### ISSUE TITLE
numerical instability in beta dist?

### ISSUE THREAD

**Issue by muirjm** [justinbois/distribution-explorer#1]
Playing with the beta distribution, I noticed strange things like the following:
![image](https://user-images.githubusercontent.com/14828781/76492481-95cf2100-63ed-11ea-8f1b-ff38fc35c01b.png)
This should be symmetric about theta=0.5, clearly not.
Basically whenever (the parameter) beta is <1, things blow up at the RH boundary (theta=1).
Zooming in, we see that the grid point theta=0 is being rightly excluded:
![image](https://user-images.githubusercontent.com/14828781/76492626-ee062300-63ed-11ea-9127-a07f24959aa3.png)
while theta=1 is not,
![image](https://user-images.githubusercontent.com/14828781/76492770-41787100-63ee-11ea-8202-ab1a905fc962.png)
which I suspect is blowing up in expressions of logprob, of form log(1-theta). Not yet sure where the fix should be though.

**Comment by justinbois** [comment]
Fixed.
