### ISSUE TITLE
Wrong Gamma functions

### ISSUE THREAD

**Issue by ghaffarialireza** [justinbois/distribution-explorer#5]
Hi, first of all, thank you for the great work; I've always been looking for something like this. Secondly, the Gamma function [here](https://distribution-explorer.github.io/background/special_functions.html#gamma-function) and afterward should have an \( e^{-t} \) instead of \( e^t \).

**Comment by justinbois** [comment]
This is a great catch! Thank you! I fixed it in the repo and it'll be live on the website soon.
